### ISSUE TITLE
Undefined function ImageCreate() in /www/lib/phpqrcode/qrimage.php:74

### ISSUE THREAD

**Issue by bavarialogy** [saadel/qrcode-scan#4]
Hello there,

this looks like somewhat of a stale project but I just tried setting the application up to see if it can help to address one usecase that I currently have. I have cloned the repo, adjusted database settings and imported the SQL example. I am seeing this error upon opening index.php:

`Fatal error: Uncaught Error: Call to undefined function ImageCreate() in /www/lib/phpqrcode/qrimage.php:74 Stack trace: #0 /www/lib/phpqrcode/qrimage.php(32): QRimage::image(Array, 4, 2, 16777215, 0) #1 /www/lib/phpqrcode/qrencode.php(513): QRimage::png(Array, 'qrs/qrcodescan....', 4, 2, false, 16777215, 0) #2 /www/lib/phpqrcode/qrencode.php(286): QRencode->encodePNG('QR Code Scan', 'qrs/qrcodescan....', false) #3 /www/index.php(71): QRcode::png('QR Code Scan', 'qrs/qrcodescan....', 'L', 4, 2) #4 {main} thrown in /www/lib/phpqrcode/qrimage.php on line 74`

It seems that there is no definition of ImageCreate() anywhere inside the repository files. Am I missing some dependency?

**Comment by bavarialogy** [comment]
Solved: The php module "gd" was missing in my Docker image. Closing.
